pom.xml
New Maven Findbugs plugin is compatible with Java 8.
(Refs #25)
=> Re-adds FindBugs analysis

pom.xml, src/main/java/nl/tudelft/jpacman/level/PlayerCollisions.java
Various updates to the pom file related to licensing, site generation, updates for the dependencies and plugins, and javadocs.
=> Mvn updates

pom.xml
This allows for releases (and only releases) to be pushed to the Nexus repo on the DevHub server. You'll still need to add your personal credentials to `~/.m2/settings.xml` to authenticate when uploading your release artifact.
=> Added Nexus distribution repository to pom.xml.

pom.xml
Releasing 6.1.1 in order to populate the nexus repo.
=> Ready to release 6.1.x.

checkstyle.xml, pom.xml, src-assembly.xml, src/main/java/nl/tudelft/jpacman/PacmanConfigurationException.java, src/main/java/nl/tudelft/jpacman/sprite/SpriteStore.java, src/test/java/nl/tudelft/jpacman/LauncherSmokeTest.java, src/test/java/nl/tudelft/jpacman/board/BoardTest.java, src/test/java/nl/tudelft/jpacman/level/LevelTest.java, src/test/java/nl/tudelft/jpacman/npc/ghost/NavigationTest.java, src/test/java/nl/tudelft/jpacman/sprite/SpriteTest.java
Updated the pom to the latest versions of some plugins.
Resolved problem in assembly plugin.
Addressed various checkstyle issues.
=> Updated pom & checkstyle

src/main/java/nl/tudelft/jpacman/Launcher.java, src/main/java/nl/tudelft/jpacman/board/BoardFactory.java, src/main/java/nl/tudelft/jpacman/level/LevelFactory.java, src/main/java/nl/tudelft/jpacman/level/MapParser.java, src/main/java/nl/tudelft/jpacman/sprite/AnimatedSprite.java
Running
mvn findbugs:findbugs site
gave a couple of warnings. These are addressed in this pull request.
=> Addressed issues identified by FindBugs

pom.xml
As not all lab computers are ready for jdk 8...
=> Switching back to jdk7

doc/scenarios.md
=> Changed all occurences of food to pellet

pmd-rules.xml, pom.xml, src/main/java/nl/tudelft/jpacman/ui/PacManUI.java, src/main/java/nl/tudelft/jpacman/ui/PacManUiBuilder.java, src/main/java/nl/tudelft/jpacman/ui/ScorePanel.java, src/test/java/nl/tudelft/jpacman/board/BoardFactoryTest.java, src/test/java/nl/tudelft/jpacman/board/BoardTest.java, src/test/java/nl/tudelft/jpacman/board/OccupantTest.java, src/test/java/nl/tudelft/jpacman/board/SquareTest.java, src/test/java/nl/tudelft/jpacman/level/LevelTest.java, src/test/java/nl/tudelft/jpacman/npc/ghost/NavigationTest.java
This permits extensions to configure the way the score is presented, and to include additional data in the score.
Builds upon #51.
=> Open Up Score Panel for Extension

src/main/java/nl/tudelft/jpacman/level/Player.java, src/main/java/nl/tudelft/jpacman/level/PlayerFactory.java
We want to be able to extend the Player class so that we are able to add properties to Players.
=> Enable Player subclassing.

pom.xml, src/main/java/nl/tudelft/jpacman/PacmanConfigurationException.java, src/main/java/nl/tudelft/jpacman/board/Square.java, src/main/java/nl/tudelft/jpacman/board/Unit.java, src/main/java/nl/tudelft/jpacman/game/SinglePlayerGame.java, src/main/java/nl/tudelft/jpacman/level/Level.java, src/main/java/nl/tudelft/jpacman/sprite/AnimatedSprite.java, src/test/java/nl/tudelft/jpacman/board/OccupantTest.java
Various changes while experimenting with coverage.
* Update pom dependencies and plugins to latest versions
* Remove some dead code
* Strengthen some of the assertion checking
* Add jacoco as coverage checker to maven configuration.
=> Various changes to better support coverage analysis

src/main/java/nl/tudelft/jpacman/annotations/ParameterizedAssignment.java
Introducing a marker annotation to the framework to mark the within borders assignment for autograding
=> Assignment annotations

doc/scenarios.md, pom.xml, src/main/java/nl/tudelft/jpacman/Launcher.java, src/test/java/nl/tudelft/jpacman/cucumber/CucumberTest.java, src/test/java/nl/tudelft/jpacman/cucumber/StateNavigationSteps.java, src/test/resources/features/startup.feature
This simple implementation of user story 1 provides an example of how to implement Cucumber tests for the various stories and scenarios in `doc/scenarios.md`.
=> Added a simple Cucumber test.

.pmd, README.md, pmd-rules.xml, pom.xml
=> Bumping version 6.4.0

src/main/java/nl/tudelft/jpacman/annotations/ParameterizedAssignment.java
Added jdoc to show how the annotation should be used.
=> added an example for the students in the javadoc of the Parameterized Annotation

pom.xml, src-assembly.xml, src/main/java/nl/tudelft/jpacman/board/Board.java, src/main/java/nl/tudelft/jpacman/board/Unit.java, src/main/java/nl/tudelft/jpacman/level/CollisionInteractionMap.java, src/main/java/nl/tudelft/jpacman/npc/ghost/Clyde.java, src/main/java/nl/tudelft/jpacman/npc/ghost/GhostColor.java, src/main/java/nl/tudelft/jpacman/sprite/SpriteStore.java, src/test/java/nl/tudelft/jpacman/cucumber/StateNavigationSteps.java
Fixed various issues that were reported by IntelliJ inspect code on master.
1. Right click the project `jpacman-framework`
* Click `Analyze`
* Click `Inspect code...`
* After the inspection is done, observe a new tab `Inspection` with the corresponding warnings
* Collapsed an XML statement
* Changed for-loop to foreach loop
* Simplified if-statement
* Simplified generic arguments of maps. They can be inferred by the left-hand side declaration
* Fixed Javadoc invalid reference to the `getGame` method
=> Fix issues reported by intellij inspect code

src/main/java/nl/tudelft/jpacman/Launcher.java
I noticed that addSinglePlayerKeys method was too long and it could be refactored by extracting repeated portions of code into a helper method.
=> addSinglePlayerKeys small refactoring

doc/scenarios.md
Fix tiny typo in story 2. It's a minor thing, but for some reason it was stressing me out :D
=> fix typo in story 2

pom.xml, src/main/java/nl/tudelft/jpacman/ui/ScorePanel.java, src/test/java/nl/tudelft/jpacman/LauncherSmokeTest.java, src/test/java/nl/tudelft/jpacman/board/BoardFactoryTest.java, src/test/java/nl/tudelft/jpacman/board/BoardTest.java, src/test/java/nl/tudelft/jpacman/board/OccupantTest.java, src/test/java/nl/tudelft/jpacman/board/SquareTest.java, src/test/java/nl/tudelft/jpacman/level/LevelTest.java, src/test/java/nl/tudelft/jpacman/npc/ghost/NavigationTest.java, src/test/java/nl/tudelft/jpacman/sprite/SpriteTest.java
Experimental branch with JUnit 5 version of JPacman.
This move also implies a systematic adoption of AssertJ (and dropping of hamcrest).
All seems to working fine -- still exploring the impact on some of the exercises.
Feedback welcome.
(Do not merge yet).
=> Move to JUnit 5

src/main/java/nl/tudelft/jpacman/Launcher.java, src/main/java/nl/tudelft/jpacman/board/Board.java, src/main/java/nl/tudelft/jpacman/board/Square.java, src/main/java/nl/tudelft/jpacman/board/Unit.java, src/main/java/nl/tudelft/jpacman/level/CollisionInteractionMap.java, src/main/java/nl/tudelft/jpacman/level/LevelFactory.java, src/main/java/nl/tudelft/jpacman/npc/NPC.java, src/main/java/nl/tudelft/jpacman/npc/ghost/Blinky.java, src/main/java/nl/tudelft/jpacman/npc/ghost/Clyde.java, src/main/java/nl/tudelft/jpacman/npc/ghost/Inky.java, src/main/java/nl/tudelft/jpacman/npc/ghost/Navigation.java, src/main/java/nl/tudelft/jpacman/npc/ghost/Pinky.java, src/main/java/nl/tudelft/jpacman/ui/PacManUI.java, src/main/java/nl/tudelft/jpacman/ui/PacManUiBuilder.java, src/test/java/nl/tudelft/jpacman/npc/ghost/NavigationTest.java
This pull request removes some warning suppressions, puts others in a smaller scope, and improves formatting by putting type annotations right before types instead of before method modifiers.
=> Improve nullness annotations

src/main/java/nl/tudelft/jpacman/npc/ghost/Inky.java, src/main/java/nl/tudelft/jpacman/npc/ghost/Pinky.java
Their types are automatically inferred.
=> There is no need to annotate local variables

pom.xml
In line with https://github.com/typetools/checker-framework/pull/1249
=> Update maven compiler plugin to latest version.

pmd-rules.xml, src/main/java/nl/tudelft/jpacman/Launcher.java, src/main/java/nl/tudelft/jpacman/level/DefaultPlayerInteractionMap.java, src/main/java/nl/tudelft/jpacman/ui/ButtonPanel.java, src/main/java/nl/tudelft/jpacman/ui/PacManUI.java, src/main/java/nl/tudelft/jpacman/ui/PacManUiBuilder.java, src/test/java/nl/tudelft/jpacman/e2e/framework/startup/StartupTest.java
Various static analysis improvements, possible after dropping Cobertura thus allowing use of Java 8 features such as lambdas.
=> Static analysis

pom.xml, src/main/java/nl/tudelft/jpacman/Launcher.java, src/main/java/nl/tudelft/jpacman/level/MapParser.java
In separate commits:
- Replace tabs by spaces for two files involved
- Open up addSquare so that parser extensions can use it
- Move resource handling from Launcher to map parser.
=> Move resource handling from launcher to parser

AUTHORS.md
This is in conjunction with https://github.com/SERG-Delft/jpacman-assignment/pull/13
=> Add MD Authors file
